[PARSER]
    Name        csv_ospf
    Format      regex
    Regex       ^(?<watcher_time>[^,]+),(?<watcher_name>[^,]+),(?<event_name>[^,]+),(?<event_object>[^,]+),(?<event_status>[^,]+),(?<rest>.*)$
    Time_Key    watcher_time
    Time_Format %Y-%m-%dT%H:%M:%S.%LZ
    Time_Keep   On

