frr version 8.4.1_git
frr defaults traditional
hostname router6
no ipv6 forwarding
!
password zebra
!
ip route 6.6.6.6/32 192.168.36.3
!
interface eth1
 ip address 192.168.36.6/24
 ip ospf 1 area 0
 ip ospf cost 66
 ip ospf priority 100
 link-params
  enable
  admin-grp 0x647a0001
  max-bw 1.25e+07
  metric 6
  max-bw 1e+08
  unrsv-bw 0 1.23e+06
  unrsv-bw 5 1.23e+06
  exit-link-params
exit
!
interface lo
 ip address 10.10.10.6/32
 ip ospf 1 area 0
exit
!
router ospf 1
 ospf router-id 10.10.10.6
 redistribute static metric 11 route-map STATIC->OSPF
 capability opaque
 mpls-te on
 mpls-te router-address 10.10.10.6
exit
!
access-list AL_STATIC_OSPF seq 5 permit 6.6.6.6/32
!
route-map STATIC->OSPF permit 10
 match ip address AL_STATIC_OSPF
exit
!
