frr version 8.4.1_git
frr defaults traditional
hostname router2
no ipv6 forwarding
!
interface eth1
 ip address 192.168.23.1/24
 ip ospf 1 area 0
 ip ospf network point-to-point
 link-params
  enable
  metric 23
  unrsv-bw 0 1.2e+06
  unrsv-bw 1 1.21e+06
  unrsv-bw 2 1.22e+06
  unrsv-bw 3 1.23e+06
  unrsv-bw 4 1.24e+06
  unrsv-bw 5 1.25e+06
  admin-grp 0x647a0001
 exit-link-params
exit
!
interface lo
 ip address 10.10.10.2/32
 ip ospf 1 area 0
exit
!
router ospf 1
 ospf router-id 10.10.10.2
 capability opaque
 mpls-te on
 mpls-te router-address 10.10.10.2
exit
!
